name: Continuos Integration
on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4  

            - name: Run Python Linter
              uses: advanced-security/python-lint-code-scanning-action@v1
              with:
                linter: flake8

    docker:
      runs-on: ubuntu-latest
      steps:
      -
      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      
      # -
      #   name: Login to Docker Hub
      #   uses: docker/login-action@v4
      #   with:
      #     username: ${{ vars.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v4
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v4
      -
        name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: false
          tags: user/app:latest
    
    tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v5
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.x'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Test with pytest
          run: |
            pip install pytest pytest-cov
            pytest test/test.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

    discord:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4

      - name: Discord Commits
        uses: chase-roohms/discord-notify@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEB_HOOK }}
          content: 'Actions de Integração funcionando com Sucesso!'
          
          embed-titles: 'Build Status'
          embed-descriptions: 'All tests passed successfully'
          embed-colors: '00FF00'
          embed-footers: 'GitHub Actions'
          embed-timestamps: 'now'