name: Continuos Integration
on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4  

            - name: Run Python Linter
              uses: advanced-security/python-lint-code-scanning-action@v1
              with:
                linter: flake8